// ===================================================================
// ON-COURT ROLE: position split bars + play-by-play stats
// ===================================================================
const POSITION_LABELS = [
  { key: 'pg_pct', label: 'PG' },
  { key: 'sg_pct', label: 'SG' },
  { key: 'sf_pct', label: 'SF' },
  { key: 'pf_pct', label: 'PF' },
  { key: 'c_pct', label: 'C' },
];

function renderPositionAndPbp(playerId) {
  const seasons = pbpByPlayer.get(playerId) || [];

  if (seasons.length === 0) {
    $('#pc-pbp-panel').style.display = 'block';
    $('#pc-pbp-sub').textContent = 'Play-by-play tracking begins in the 1996/97 season — not available for this player\u2019s career.';
    $('#pc-position-bars').innerHTML = '<div class="no-data-note">No data.</div>';
    $('#pc-pbp-stats').innerHTML = '';
    return;
  }

  $('#pc-pbp-panel').style.display = 'block';
  $('#pc-pbp-sub').textContent = 'Career-average position mix and per-season playmaking/discipline stats (1996/97 onward).';

  // average position split across all tracked seasons (weighted by games played
  // isn't available here directly, so simple mean across seasons is used)
  const avgPos = {};
  POSITION_LABELS.forEach(p => {
    const vals = seasons.map(s => s[p.key]).filter(v => v != null);
    avgPos[p.key] = vals.length ? vals.reduce((a, b) => a + b, 0) / vals.length : 0;
  });

  $('#pc-position-bars').innerHTML = POSITION_LABELS.map(p => {
    const pct = avgPos[p.key];
    return `<div class="position-bar-row">
      <span class="position-bar-label">${p.label}</span>
      <div class="position-bar-track"><div class="position-bar-fill" style="width:${pct}%"></div></div>
      <span class="position-bar-pct">${pct.toFixed(0)}%</span>
    </div>`;
  }).join('');

  // most recent season's play-by-play stats for the discipline/playmaking grid
  const latest = seasons[seasons.length - 1];
  const cells = [
    { l: 'On-court +/- per 100', v: latest.on_court_plus_minus != null ? (latest.on_court_plus_minus > 0 ? '+' : '') + fmtNum(latest.on_court_plus_minus, 1) : '—', cls: latest.on_court_plus_minus > 0 ? 'positive' : latest.on_court_plus_minus < 0 ? 'negative' : '' },
    { l: 'Net rating swing', v: latest.net_plus_minus != null ? (latest.net_plus_minus > 0 ? '+' : '') + fmtNum(latest.net_plus_minus, 1) : '—', cls: latest.net_plus_minus > 0 ? 'positive' : latest.net_plus_minus < 0 ? 'negative' : '' },
    { l: 'Pts generated by assists', v: fmtInt(latest.pts_generated_by_ast) },
    { l: 'And-1s', v: fmtInt(latest.and1) },
    { l: 'Shooting fouls drawn', v: fmtInt(latest.shooting_foul_drawn) },
    { l: 'Shooting fouls committed', v: fmtInt(latest.shooting_foul_committed) },
    { l: 'Bad-pass turnovers', v: fmtInt(latest.bad_pass_to) },
    { l: 'FGA blocked', v: fmtInt(latest.fga_blocked) },
  ];
  $('#pc-pbp-stats').innerHTML = `<div class="pbp-stat-grid">${cells.map(c =>
    `<div class="pbp-stat-cell"><div class="v ${c.cls || ''}">${c.v}</div><div class="l">${c.l}</div></div>`
  ).join('')}</div>
  <div style="margin-top:10px; font-family:var(--font-mono); font-size:11px; color:var(--chalk-dim);">Showing ${latest.season} season</div>`;
}
