"""Team colors and badge codes per franchise lineage (factual color data, not logo artwork)."""

TEAM_COLORS = {
    'Atlanta Hawks': dict(primary='#E03A3E', secondary='#26282A', code='ATL'),
    'Boston Celtics': dict(primary='#007A33', secondary='#BA9653', code='BOS'),
    'Brooklyn Nets': dict(primary='#000000', secondary='#FFFFFF', code='BKN'),
    'Charlotte Hornets': dict(primary='#1D1160', secondary='#00788C', code='CHA'),
    'Chicago Bulls': dict(primary='#CE1141', secondary='#000000', code='CHI'),
    'Cleveland Cavaliers': dict(primary='#860038', secondary='#FDBB30', code='CLE'),
    'Dallas Mavericks': dict(primary='#00538C', secondary='#002B5E', code='DAL'),
    'Denver Nuggets': dict(primary='#0E2240', secondary='#FEC524', code='DEN'),
    'Detroit Pistons': dict(primary='#C8102E', secondary='#1D42BA', code='DET'),
    'Golden State Warriors': dict(primary='#1D428A', secondary='#FFC72C', code='GSW'),
    'Houston Rockets': dict(primary='#CE1141', secondary='#000000', code='HOU'),
    'Indiana Pacers': dict(primary='#002D62', secondary='#FDBB30', code='IND'),
    'Los Angeles Clippers': dict(primary='#C8102E', secondary='#1D428A', code='LAC'),
    'Los Angeles Lakers': dict(primary='#552583', secondary='#FDB927', code='LAL'),
    'Memphis Grizzlies': dict(primary='#5D76A9', secondary='#12173F', code='MEM'),
    'Miami Heat': dict(primary='#98002E', secondary='#F9A01B', code='MIA'),
    'Milwaukee Bucks': dict(primary='#00471B', secondary='#EEE1C6', code='MIL'),
    'Minnesota Timberwolves': dict(primary='#0C2340', secondary='#236192', code='MIN'),
    'New Orleans Pelicans': dict(primary='#0C2340', secondary='#C8102E', code='NOP'),
    'New York Knicks': dict(primary='#006BB6', secondary='#F58426', code='NYK'),
    'Oklahoma City Thunder': dict(primary='#007AC1', secondary='#EF3B24', code='OKC'),
    'Orlando Magic': dict(primary='#0077C0', secondary='#000000', code='ORL'),
    'Philadelphia 76ers': dict(primary='#006BB6', secondary='#ED174C', code='PHI'),
    'Phoenix Suns': dict(primary='#1D1160', secondary='#E56020', code='PHX'),
    'Portland Trail Blazers': dict(primary='#E03A3E', secondary='#000000', code='POR'),
    'Sacramento Kings': dict(primary='#5A2D81', secondary='#63727A', code='SAC'),
    'San Antonio Spurs': dict(primary='#000000', secondary='#C4CED4', code='SAS'),
    'Toronto Raptors': dict(primary='#CE1141', secondary='#000000', code='TOR'),
    'Utah Jazz': dict(primary='#002B5C', secondary='#F9A01B', code='UTA'),
    'Washington Wizards': dict(primary='#002B5C', secondary='#E31837', code='WAS'),
    # Defunct franchises (approximate historical colors)
    'Anderson Packers': dict(primary='#8B4513', secondary='#FFFFFF', code='AND'),
    'Baltimore Bullets (original)': dict(primary='#1B3F8B', secondary='#FF6600', code='BAL'),
    'Chicago Stags': dict(primary='#C8102E', secondary='#000000', code='CHS'),
    'Cleveland Rebels': dict(primary='#7B0046', secondary='#FFFFFF', code='CLR'),
    'Detroit Falcons': dict(primary='#000000', secondary='#C8102E', code='DTF'),
    'Indianapolis Jets': dict(primary='#002D62', secondary='#FFFFFF', code='INJ'),
    'Indianapolis Olympians': dict(primary='#002D62', secondary='#C8102E', code='INO'),
    'Pittsburgh Ironmen': dict(primary='#000000', secondary='#FFB81C', code='PIT'),
    'Providence Steamrollers': dict(primary='#00205B', secondary='#C8102E', code='PRO'),
    'Sheboygan Red Skins': dict(primary='#8B2331', secondary='#FFFFFF', code='SHE'),
    'St. Louis Bombers': dict(primary='#002B5C', secondary='#C8102E', code='STB'),
    'Toronto Huskies': dict(primary='#000000', secondary='#FFFFFF', code='TRH'),
    'Washington Capitols': dict(primary='#002B5C', secondary='#C8102E', code='WSC'),
    'Waterloo Hawks': dict(primary='#8B0000', secondary='#FFFFFF', code='WAT'),
}
